version: "3.1"

services:
  db:
    image: mariadb:latest
    container_name: db
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: db
      MARIADB_USER: user
      MARIADB_PASSWORD: password
    ports:
      - 3306:3306
