name: test
run-name: ${{ github.actor }} new test.
on: [push]
jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Cache composer dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: composer-${{ hashFiles('api/composer.lock') }}
      
      - name: Run composer install
        run: |
          cd api
          composer install -n --prefer-dist
        env:
          APP_ENV: testing

      - name: Prepare Laravel Application
        run: |
          cd api
          cp .env.example .env
          php artisan key:generate
      
      - name: Run tests
        run: |
          cd api
          php artisan app:rsa
          php artisan test --parallel
        env:
          APP_ENV: testing

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: ./api/storage/logs